name: titeo_game
description: "Game ghép chữ viral Tí Tẹo"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.8

  # Logic & State Management
  http: ^1.2.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2 

  # Firebase (Bỏ comment khi đã cài đặt Firebase)
  # firebase_core: ^2.24.2
  # cloud_firestore: ^4.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true